"""empty message

Revision ID: 0001_create_fcuser
Revises: 
Create Date: 2021-07-11 03:18:01.774369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001_create_fcuser'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'fcuser',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('userid', sa.String(length=32), nullable=False),
        sa.Column('username', sa.String(length=16), nullable=False),
        sa.Column('password', sa.String(length=200), nullable=False),
        sa.Column('email', sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('userid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fcuser')
    # ### end Alembic commands ###
